apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalyst.ai
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
        - name: catalyst.ai
          image: atulbargotra/catalyst.ai:latest
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: catalyst.ai
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 8090